baseURL = "https://brianp.de/"
languageCode = "en-us"
title = "Brian Pfretzschner"
theme = "brianp"
enableEmoji = true

[author]
  name = "Brian Pfretzschner"

[params]
  description = "Personal home page and blog of Brian Pfretzschner"
  dateform = "02.01.2006"
  dateformShort = "2. January"
  dateformNum = "2006-01-02"
  dateformNumTime = "2006-01-02"

  homeSubtitle = "Software Developer & Electronics Enthusiast"
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  
  relatedPosts = true

  code_copy_button = false

  customCSS = ["css/custom.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "Projects"
    url = "projects/"
    weight = 20

  [[menu.main]]
    name = "Quotes"
    url = "quotes"
    weight = 30

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 40