baseURL = "https://brianp.de/"
languageCode = "en-us"
title = "Brian Pfretzschner"
theme = "brianp"
enableEmoji = true
enableGitInfo = true

[author]
  name = "Brian Pfretzschner"

[params]
  description = "Personal home page and blog of Brian Pfretzschner"
  dateform = "02.01.2006"
  dateformShort = "2. January"
  dateformNum = "2006-01-02"
  dateformNumTime = "2006-01-02"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "Projects"
    url = "projects/"
    weight = 20

  [[menu.main]]
    name = "Glossary"
    url = "glossary/"
    weight = 30

  [[menu.main]]
    name = "Quotes"
    url = "quotes"
    weight = 40
